//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectRemover.Package {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProjectRemover.Package.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -------- Error --------.
        /// </summary>
        internal static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -------- Finished Project Remover --------.
        /// </summary>
        internal static string info_FinishedProjectRemover {
            get {
                return ResourceManager.GetString("info_FinishedProjectRemover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No unused project found..
        /// </summary>
        internal static string info_NoUnusedProjectFound {
            get {
                return ResourceManager.GetString("info_NoUnusedProjectFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully removed {0} Projects:{1}.
        /// </summary>
        internal static string info_RemovedProjects {
            get {
                return ResourceManager.GetString("info_RemovedProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -------- Starting Project Remover --------.
        /// </summary>
        internal static string info_StartingProjectRemover {
            get {
                return ResourceManager.GetString("info_StartingProjectRemover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -------- Warning --------.
        /// </summary>
        internal static string warning {
            get {
                return ResourceManager.GetString("warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not delete the project [{0}] from the GlobalSection(TeamFoundationVersionControl) in the solution file..
        /// </summary>
        internal static string warning_CouldNotDeleteProjectFromTeamFoundationVersionControlSection {
            get {
                return ResourceManager.GetString("warning_CouldNotDeleteProjectFromTeamFoundationVersionControlSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Cannot remove Projects while building..
        /// </summary>
        internal static string warning_RemoveProjectsWhileBuilding {
            get {
                return ResourceManager.GetString("warning_RemoveProjectsWhileBuilding", resourceCulture);
            }
        }
    }
}
